### ISSUE TITLE
After the last update (2.02) all devices are gone

### ISSUE THREAD

**Issue by fkey3** [nattlip/com.jilles.x10.2#1]
Today the new version of the app was automatically downloaded.
After that download X10 stopped working.
Turned out all devices are gone corruoted :-(
Restart of homey did not solve the problem
![65603459-9f62-4654-a23e-8e3ff32a4c7f](https://user-images.githubusercontent.com/42219340/45902344-73ef7200-bde6-11e8-88d7-16150f31720a.jpeg)
![3c6ad4e6-2796-430e-bee5-fc86f4e5280e](https://user-images.githubusercontent.com/42219340/45902346-73ef7200-bde6-11e8-9adb-4b9decbc5d89.jpeg)

**Comment by nattlip** [comment]
all devices must be repaired

**Comment by nattlip** [comment]
updating the app to V2 implies yopu have to repair all devices because a virtual device class is added , so yo can implement a socket or dim x10 as a light, all on and off can be implemented from a flow

**Comment by fkey3** [comment]
Tip for future changes. If a software update has major interface changes (require a repair) please create a new app.
I do not like to run into a failing system just by automatic updates...

Came home in a dark house, had to take my cm10pro to get some light in the house again.
Thats really bad...

**Comment by nattlip** [comment]
athom doesnt allow a second app for the sme product, i have asked them , they allowed it once for the rfxcom app , but for the x10 it was forbidden to me to publish a second x10 app , i tried but it was not allowed

and i domt know the emails of the users of my apps cant warn them , yes it could via the forum or slack but i dont read them every day, so i think other users also dont . i have my automatic updates off , indeed to prevent disasters with updates

**Comment by fkey3** [comment]
Thanks for your clear reply. Sounds like Athom does not understand proper configuration management. They should be the ones enforcing a new app! To make sure there product is stable. (Especially since there is no backup to fall back to)
Just switched off auomatic updates too. (And fear for the release of v2)
