### ISSUE TITLE
“Report an issue” link corrupt

### ISSUE THREAD

**Issue by fkey3** [nattlip/com.jilles.x10.2#2]
The report an issue link on the app.athom.com page is corrupt
![bad0f1bd-12b3-4675-99f3-2fada23bda46](https://user-images.githubusercontent.com/42219340/45904547-b7011380-bded-11e8-8466-a8520f2d5454.jpeg)
![0dd86e36-3f21-4565-bae7-b1d758ba2058](https://user-images.githubusercontent.com/42219340/45904548-b7011380-bded-11e8-99f5-f6c85a435f2e.jpeg)

**Comment by nattlip** [comment]
strange is , it is the correct link in json  https://github.com/nattlip/com.jilles.x10.2/issues

**Comment by fkey3** [comment]
![3bd6eeb0-03fd-48fb-8c04-7eec0f439435](https://user-images.githubusercontent.com/42219340/45973398-a1365d00-c03e-11e8-9a04-e53d909b98f2.jpeg)

**Comment by nattlip** [comment]
repaired

**Comment by fkey3** [comment]
Working fine now!
I wasn’t aware that updates of the page 
https://apps.athom.com/app/com.jilles.x10 are also released via the app realease.
