### ISSUE TITLE
X10 rf recieve no longer working

### ISSUE THREAD

**Issue by fkey3** [nattlip/com.jilles.x10.2#3]
Since the upgrade to v2.02 homey does not respond to recieve RF anymore.
Removed the devices and created them again.
When I drag x10 into the WHEN and out in a direct RF call the flow is not triggered.
When I drag in a device into the WHEN with a recieve no trigger of the flow either

Worked perfectly fine until last week (before the update)

**Comment by nattlip** [comment]
i will look into the flow bug

**Comment by fkey3** [comment]
Small update: MS13e receive RF commands do work.
I created a “fake” ms13e device and named it after the RF signal that is send from my CM15pro. It nicely triggers the flow! 
So it seems signals that are not coupled to a device are not received anymore.
But I use them a lot: X10 RF remote and I have my CM15pro send RF signals to homes for certain states.
So my workaround is now: create a lot of MS13e devices to catch the RF

**Comment by nattlip** [comment]
thats correct i am looking in to it

**Comment by nattlip** [comment]
repaired in 2.0.4 is submitted to app store waiting approval

**Comment by fkey3** [comment]
Thanks!!
I’ll test it and then close the issue..

**Comment by fkey3** [comment]
Just tested 2.05. Unfortunately still not working.
![432a7642-22b1-4e1c-93df-febef2c5fe17](https://user-images.githubusercontent.com/42219340/46228934-fedee800-c363-11e8-8ede-bd00e21615ec.jpeg)
![23ab128f-b7eb-402a-9e1b-13a34e7af336](https://user-images.githubusercontent.com/42219340/46228937-fedee800-c363-11e8-85b9-40e4b9d2fe1d.jpeg)

**Comment by nattlip** [comment]
and in 2.o.5 released yesterday evening

**Comment by fkey3** [comment]
@nattlip , Hi Jilles,
I tested it at 2.05.it did not function.
Do I use it the wrong way (it did work like this before 2.02..)

**Comment by nattlip** [comment]
but he receives d 6 on , but no ms13e commands, but the commandss send from the paired ms13e should be send to the device capabilitie. . i dont understnad what works and what not

**Comment by nattlip** [comment]
i do iunderstand , i have a flow with a ms13e if he detects movement homey says something

**Comment by nattlip** [comment]
![aantekening 1](https://user-images.githubusercontent.com/7040452/46249797-69a92580-c42f-11e8-8a1d-0159d33cd396.png)


this works

**Comment by nattlip** [comment]
i ll check it tomorrow evening ,

**Comment by nattlip** [comment]
it works with me the flow above works , if x10.2 recieves the above code from 433 signal homey speaks , i have now 2.05 from the app store. So i dont understand it is not working with you @fkey3

**Comment by fkey3** [comment]
Tested again with the same flow as your example (speech), it works.
Changed my flow to “received X10 command”, it works!😀

Dont know what went wrong yesterday (the screenshot shows exactly the same command I have now)
Thanks for your patience! 😉

**Comment by nattlip** [comment]
glad it works
________________________________
Van: fkey3 <notifications@github.com>
Verzonden: zondag 30 september 2018 21:53
Aan: nattlip/com.jilles.x10.2
CC: nattlip; Mention
Onderwerp: Re: [nattlip/com.jilles.x10.2] X10 rf recieve no longer working (#3)


Tested again with the same flow as your example (speech), it works.
Changed my flow to “received X10 command”, it works!😀

Dont know what went wrong yesterday (the screenshot shows exactly the same command I have now)
Thanks for your patience! 😉

**Comment by phgmhendrix** [comment]
I use an X13 transceiver. Sending commands to the AM12G appliance works perfectly.
However... receiving X10 command does not. One of my on/off devices reacts on housecode D with ID 1, however if I create a flow that is triggered by D1 nothing happens.
Can I test/debug something to help or am I doing something wrong?

**Comment by fkey3** [comment]
Your hardware setup will not work:
1 homey is able to send and receive X10 RF commands, not X10 powerline commands.
2 your transceiver is able to transfer RF to powerline. 
So in your setup Homey is able to operate the X10 devices, but your setup is not able to create a RF command that homey can receive.

You need to add a device that sends X10-RF commands based on X10 powerline commands.
I have a CM15pro that runs amacro based on recieved X10 powerline. The macro in its turn sends a X10 RF that is received by homey.

You can buy CM15pro cheap 2ndhand...

**Comment by phgmhendrix** [comment]
Clear!
I was under the presumption that the X13 was a transceiver both ways. I'll pick up a CM15Pro somewhere.
