### ISSUE TITLE
When creating a X10 device, virtual device dropdown not available

### ISSUE THREAD

**Issue by fkey3** [nattlip/com.jilles.x10.2#4]
creating a new X10device fails 1out of 10 times
After filling the housecode and unticode the deviceType and virtualDeviceClass dropdown do not work.

Workaround: Cancel and creating it again work. (But after a few it fails again)
![2dc48bfc-ac99-48fe-9612-6eb4ecc2481f](https://user-images.githubusercontent.com/42219340/45973802-c081ba00-c03f-11e8-9c9a-6caf034ff2ea.jpeg)

**Comment by nattlip** [comment]
well that worked in prevous versions of homey firmware ewithout a problem, the data of the dropdown menu are now sometimes available

**Comment by fkey3** [comment]
@nattlip, Hi jilles, do I understand correctly that this is a homey firmware issue, so not something you can solve?
(in that case I will close the issue)
(Do you know where I should report an issue like this to Athom?)

**Comment by fkey3** [comment]
Ok thanks for the explanation.
Is this same issue causing the empty page (sometimes) when I create a new device?
1 in devices press the plus
2 select X10.2
3 select the icon
4 empty screen (see screenshot)
![de108ea8-200e-40aa-af01-7e18e6b7bd09](https://user-images.githubusercontent.com/42219340/46305661-58d4ed00-c5b2-11e8-87f3-3e0241cbca7b.jpeg)

**Comment by nattlip** [comment]
with me it works perfectly now , without changing code added 10 devices tonight with code, do you have to many devices flows and apps on your homey then homey becomes slow . cant fix

**Comment by fkey3** [comment]
Just bought my homey a few month ago. So am just adding my 1st flows and devices.
If I already reached homeys limits that would be really really disappointing :-(
Ihave just under 60 flows and just under 70 devices (many virtual devices).
Dont consider that a lot (had a lot more running on my cm15pro, converting them to homey now)

**Comment by nattlip** [comment]
well i after restaring homey it functions good , it is a memory limitaion problem of homey
