### ISSUE TITLE
X10 stop working

### ISSUE THREAD

**Issue by MatsGrano** [nattlip/com.jilles.x10.2#5]
Hi I'm running v2.0.4 and now x10 have stop working. Every time I click on a device it says the device are currently unavailable

**Comment by nattlip** [comment]
and with the now relaesed  2.0.5 ? (this evening)

**Comment by MatsGrano** [comment]
I’m not home but what I can see on my phone it looks great :)

mvh

Mats

28 sep. 2018 kl. 19:28 skrev nattlip <notifications@github.com<mailto:notifications@github.com>>:


and with the now relaesed 2.0.5 ? (this evening)

**Comment by fkey3** [comment]
2.04 caused all devices to disappear :-( thought I had to repair again.
But luckily 2.05 repaired evetything, pffff

@nattlip strange thing is I have automatic updates switched off (after our last conveersation), but still both updates where pusehed to homey.
Is there another switch?
![f00b17d4-78db-4d4f-8e5d-f88e90b0fe98](https://user-images.githubusercontent.com/42219340/46226594-14044880-c35d-11e8-8c48-acf806c83ac0.jpeg)
![Uploading AA7EFF4C-560B-42DF-BEDC-F1F8F7C7BE7A.jpeg…]()

**Comment by fkey3** [comment]
Just found out the apps have a seperate settigng...

**Comment by nattlip** [comment]
yes you have to repair all devices when updating to V2 of the app

**Comment by MatsGrano** [comment]
I just want to inform u that the app have stop to work after the latest update

Best regards

Mats

**Comment by nattlip** [comment]
@MatsGrano can you send me a error report ?

**Comment by MatsGrano** [comment]
I will reinstall and send u a log tomorrow

Best regards

Mats

17 feb. 2019 kl. 17:51 skrev nattlip <notifications@github.com<mailto:notifications@github.com>>:


@MatsGrano<https://github.com/MatsGrano> can you send me a error report ?

**Comment by fkey3** [comment]
@MatsGrano What version are you considering as “latest update”?
I am at v2.06 and thats perfectly stable.

@nattlip i do see in the changelog an entry after the 30-09-2018 release,
at 27-01-2019. Is this an update of v2.06?
If it is, how should I install it (im already at 2.06 but its installed before 27-01!)

![32d50f7c-d400-4263-bc46-5d1d77373f25](https://user-images.githubusercontent.com/42219340/52918694-37bf2f80-32fa-11e9-877c-5333b4d12b95.jpeg)

**Comment by MatsGrano** [comment]
I was running 2.0.7 and then it stop working. When I restart the app I can get it to work once and then it crash again

Best regars

Mats Granö

Från: fkey3 <notifications@github.com>
Skickat: den 17 februari 2019 21:27
Till: nattlip/com.jilles.x10.2 <com.jilles.x10.2@noreply.github.com>
Kopia: Mats Granö <mats@gakonsult.com>; Mention <mention@noreply.github.com>
Ämne: Re: [nattlip/com.jilles.x10.2] X10 stop working (#5)


@MatsGrano<https://github.com/MatsGrano> What version are you considering as “latest update”?
I am at v2.06 and thats perfectly stable.

@nattlip<https://github.com/nattlip> i do see in the changelog an entry after the 30-09-2018 release,
at 27-01-2019. Is this an update of v2.06?
If it is, how should I install it (im already at 2.06 but its installed before 27-01!)

[32d50f7c-d400-4263-bc46-5d1d77373f25]<https://user-images.githubusercontent.com/42219340/52918694-37bf2f80-32fa-11e9-877c-5333b4d12b95.jpeg>

**Comment by fkey3** [comment]
Strange 2.07 is not even shown for update in my apps list...
![88beab51-7c16-4429-b063-d6d286d3150c](https://user-images.githubusercontent.com/42219340/52920146-c1c2c480-3309-11e9-8bbd-e581ca87a035.jpeg)
