### ISSUE TITLE
App crashed while adding “all” x10device

### ISSUE THREAD

**Issue by fkey3** [nattlip/com.jilles.x10.2#6]
Hi Jilles,
My X10 app crashed today while trying to add an “all” device.
I guess you were informed (thats what homey reports).

Here some info what happened:
I was trying to create a new device with type all.
Must say its unclear to me how It should be created. I entered the housecode, should I also add a unit code?? (Strange since I want to create a “all” device) so I did not add it.
i selected the type all and virtual device none.
And pressed the create button.
The wheel started spinning...spinning, it did not stop.
So I finally pressesd the close button (X in right top)

That is what crashed the app..
![a17cfd4f-e8e8-4151-9d0a-92ed55ecfddc](https://user-images.githubusercontent.com/42219340/46375454-c442bb80-c693-11e8-9fdd-742730ee2884.jpeg)

**Comment by nattlip** [comment]
isnt functional yet

**Comment by nattlip** [comment]
that is also clearly mentioned in the readme of the app https://community.athom.com/t/x10-app/140

**Comment by nattlip** [comment]
see post above
